### ISSUE TITLE
Add graticule to map?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#144]
Is it possible to add a graticule to a map? I found [this plugin](https://github.com/turban/Leaflet.Graticule) but I'm not sure if is possible to use it in R. For example, I would like to add a graticule to this map:

    leaflet() %>% addTiles("http://opengeofiction.net/osm_tiles/{z}/{x}/{y}.png") %>%
      setView(21.5222, 59.2097, 9)

Thanks!

**Comment by cholcomb** [comment]
I'd suggest adding a graticule WMS to the map: e.g., http://maps.ngdc.noaa.gov/arcgis/rest/services/graticule/MapServer

**Comment by ignacio82** [comment]
@cholcomb sorry for the basic question, how do you do that? Thanks!

**Comment by cholcomb** [comment]
No problem, from the prior link you click on the tiny WMS link on the top left which runs a GetCapabilities request:
http://maps.ngdc.noaa.gov/arcgis/services/graticule/MapServer/WMSServer?request=GetCapabilities&service=WMS

Search around for the Name of the layer you need, in this case it's 1-degree grid from "<Name>1-degree grid</Name>". Remove the GetCapabilities request from the URL and add in:

`leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 7) %>%
  addWMSTiles(
    "http://maps.ngdc.noaa.gov/arcgis/services/graticule/MapServer/WMSServer/",
    layers = "1-degree grid",
    options = WMSTileOptions(format = "image/png8", transparent = TRUE),
    attribution = "NOAA"
  )`

I used PNG8 because it uses less data and is available and shown on the GetCapabilities. You may also notice from the original link there's a legend link you could grab as JSON and parse: http://maps.ngdc.noaa.gov/arcgis/rest/services/graticule/MapServer/legend?f=pjson

From the GetCapabilities there's some legends you could style based on parameters you put in the request listed for legends, ala: http://maps.ngdc.noaa.gov/arcgis/services/graticule/MapServer/WmsServer?request=GetLegendGraphic%26version=1.3.0%26format=image/png%26layer=1-degree%20grid (not much to show in this case, and generally I recommend using the JSON version and styling in R/Shiny)

**Comment by ignacio82** [comment]
Thanks!
