### ISSUE TITLE
disable zoom?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#179]
Is it possible to disable zoom, and remove the + - buttons? For example:

    library(leaflet)
    leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)

Thanks!

**Comment by yihui** [comment]
In theory, you can set `zoomControl` to `false` when initializing the map, but since we don't support initialization options in this package, currently there may not be a way for you to hide the zoom control. I guess what you can do at best is to set `minZoom` and `maxZoom` to the same value when adding a tile layer (`addTiles()`): http://leafletjs.com/reference.html#tilelayer

**Comment by sibowyer** [comment]
+1 for this feature request

**Comment by bhaskarvk** [comment]
It is now possible to disable zoom control. The fix has not yet made it to cran but if you build using `devtools::install('rstudio/leaflet')` you can pass `option=leafletOptions(zoomControl=FALSE)` to your `leaflet()` call.
