### ISSUE TITLE
Implementing `get` methods.

### ISSUE THREAD

**Issue by SimonGoring** [rstudio/leaflet#202]
In trying to chain together two different leaflet plots I'd like to be able to use leaflet methods like `getCenter`.  I played around with the package a bit, but I'm having trouble understanding how the `dispatch` and `invokeMethod` might be modified to return these parameters.

Is it possible to use the [`get` methods](http://leafletjs.com/reference.html#map-get-methods) implemented in Leaflet proper as it's implemented in R now?

I can see them in `leaflet-src.js` (around line 754), but I'm not clear on this all gets put together.  Probably above my skill level :)

Thanks for the package though, it's great!

**Comment by jcheng5** [comment]
It's not really possible, not that way at least. When you call e.g. `setView(map, ...)` that doesn't actually cause any JavaScript to be executed right away; the chain of Leaflet functions is just composing a _specification_ for a Leaflet JS map to be created in the future. It's not until the widget is rendered to HTML and executed in the browser that the map object actually exists.

That being said, when you put Shiny in the mix, now you have some possibilities.

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  fluidRow(
    column(6, leafletOutput("map1")),
    column(6, leafletOutput("map2"))
  )
)

server <- function(input, output, session) {
  output$map1 <- renderLeaflet({
    leaflet() %>% addTiles()
  })
  output$map2 <- renderLeaflet({
    leaflet() %>% addTiles()
  })
  
  observe({
    b <- input$map1_bounds
    leafletProxy("map2") %>% setView(mean(c(b$west, b$east)), mean(c(b$north, b$south)), input$map1_zoom)
  })
}

shinyApp(ui, server)
```

This doesn't work perfectly because we don't have `map1`'s center, rather we approximate it by averaging the lats and longs, which is not that close to correct. We should really add `input$map1_center`, then it'd be possible to actually synchronize the map views (at least in one direction--there are some pitfalls if we want to synchronize the views in both directions).

**Comment by jcheng5** [comment]
I just added `_center`. This not only fixes the one-way synchronization but the two-way now works as well.

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  fluidRow(
    column(6, leafletOutput("map1")),
    column(6, leafletOutput("map2"))
  )
)

server <- function(input, output, session) {
  output$map1 <- renderLeaflet({
    leaflet() %>% addTiles()
  })
  output$map2 <- renderLeaflet({
    leaflet() %>% addTiles()
  })
  
  observe({
    leafletProxy("map2") %>%
      setView(lng = input$map1_center$lng,
        lat = input$map1_center$lat,
        zoom = input$map1_zoom)
  })
  observe({
    leafletProxy("map1") %>%
      setView(lng = input$map2_center$lng,
        lat = input$map2_center$lat,
        zoom = input$map2_zoom)
  })
}

shinyApp(ui, server)
```

If this isn't what you meant by "chaining" the maps, feel free to reopen the issue and elaborate.

**Comment by SimonGoring** [comment]
Amazing!  Thanks.
