### ISSUE TITLE
Strange behavior from `colorNumeric` & `colorFactor` clipping raster values (setting as NA?).

### ISSUE THREAD

**Issue by SimonGoring** [rstudio/leaflet#224]
I am using leaflet to represent some spatial data (historical tree species distributions - see [preprint](http://biorxiv.org/content/early/2015/10/24/026575) here for more information) as part of a bigger shiny app.  The branch I'm working on "[leaflet](https://github.com/PalEON-Project/Shiny/tree/leaflet)" contains the code.

There's lots to the code, but of note is that both `colorNumeric` and `colorFactor` (around line 154 in `server.R`) are exhibiting some strange behavior.  Both appear to be returning:

```
Warning in colors(.) :
  Some values were outside the color scale and will be treated as NA
```

even when I've tried to set the ranges to be greater than (or equal to) the range of the data.  I don't think it's a problem on my end, since the clipping is happening in very particular places.  In a strange geometric pattern for `colorNumeric` (see figure below) and at the boundaries between discrete levels for `colorFactor`.

Any help would be appreciated.
![leaflet_colornumeric](https://cloud.githubusercontent.com/assets/1619126/12060244/34e41b7e-af20-11e5-8d1b-b52640b36aab.png)
The `colorNumeric` clipping.

![leaflet_colorfactor](https://cloud.githubusercontent.com/assets/1619126/12060289/4d6e47ea-af21-11e5-91f5-b36c9029d64d.png)
The `colorFactor` clipping.

**Comment by jcheng5** [comment]
Is this happening with `addRasterImage`? That function reprojects the raster to match with the projection that Leaflet uses; see `leaflet::projectRasterForLeaflet`. IIRC I've found that reprojecting seems to cause the interpolated values to sometimes exceed the original max/min, I'm not sure why. Can you try running your raster through `leaflet::projectRasterForLeaflet` and see if that might be the case here?

**Comment by SimonGoring** [comment]
Yes, I've managed to fix it.  

It's happening (apparently) because even if the raster is in the native leaflet projection (which I assume is `EPSG:3857`) `addRaster` reprojects, so I've only had to add `project=FALSE`.  However, this behavior isn't described in the help, so it's not clear to me what's actually happening.  

For `colorFactor` it's reprojecting and resampling using some form of interpolation, so the edges of each class are getting lost (since they don't fit into the palette).  For `colorNumeric` it's not clear to me why some values are apparently higher than they were originally.

I'm still figuring this out, so I'm not sure how to keep debugging this problem.  My speciic problem is fixed, but I'm not sure this issue should be closed.

**Comment by tim-salabim** [comment]
The problem here is that the default method of `raster::projectRaster` is 'bilinear' which is a linear interpolation. Hence, as a result, some values may actually lie beyond the original data range. Therefore, the values passed to `leaflet::colorNumeric` should be the ones of the final re-projected raster. 

For factorial raster layers, `method = 'ngb'` should be used in `raster::projectRaster` which simply assigns the value of the nearest (neighboring) cell to the re-projected cell. Unfortunately, the raster layer needs to be explicitly transformed to a factorial raster after the reprojection as `raster::projectRaster` has no way of knowing whether integer values should be interpreted as factors or not and returns a numerical raster layer. Thus it is up to the user to set the appropriate class to the final re-projected raster layer (with `raster::as.factor`). See also my comment here:
https://github.com/rstudio/leaflet/issues/219

HTH,
Tim

**Comment by SimonGoring** [comment]
This has been resolved and is not active as far as I can see.  I'm closing this issue.

**Comment by costavale** [comment]
I still have this same error using colorFactor in addCircleMarkers, any workaround?

**Comment by JonathanD-L** [comment]
I'm getting this issue on addRasterImage at the lower end with highly right skewed data
