### ISSUE TITLE
An option to not re-zoom when new data is sent

### ISSUE THREAD

**Issue by wch** [rstudio/leaflet#27]
For example, this demo app re-zooms every time the data reloads. Because the data reloads automatically, this can be an interruption: https://winston.shinyapps.io/buses/
It would be nice to have an option to turn this off.

I'd also like to have a button that resets the zoom so it contains all the markers. Is it possible to send a command from the R side to tell it to do this?

**Comment by bungalow-bill** [comment]
Prior to the latest change, I was able to capture the current extents using something like:

    lastBounds <- isolate( input$mapID_center )

then add 

    %>% fitBounds(lastBounds$east,lastBounds$south,lastBounds$west,lastBounds$north)
 
when the map is updated.  But with the most recent change, that no longer works.

**Comment by wch** [comment]
Are you using the latest version? I pushed a fix to an issue about an hour ago.

**Comment by bungalow-bill** [comment]
Thanks, I just reinstalled it.  This is sort of working for me now, with a leaflet widget in a div named mapPlot:

       lastBounds <- isolate( input$mapPlot_bounds )
       map() %>% addTiles() %>% fitBounds(lastBounds$east,lastBounds$south,lastBounds$west,lastBounds$north)

It seems to act a bit funny at some zoom levels though, probably because the fitBounds code is being conservative.  If there was a _center value available it would probably work better to use setView() and specify the center location and the zoom level.

**Comment by wch** [comment]
Closed by #33.

**Comment by wch** [comment]
@bungalow-bill if you're still having problems, you can file a new issue.
