### ISSUE TITLE
is it intentional that addGeoJSON has no argument popup?

### ISSUE THREAD

**Issue by tim-salabim** [rstudio/leaflet#319]
I am wondering why `addGeoJSON` has no way to display popups. See this

http://stackoverflow.com/questions/40267515/r-geojson-feature-display-with-leaflet

question on SO

**Comment by bhaskarvk** [comment]
There are 3 ways in which you can do it.

1) Have a property  called 'popup' for each feature in your geojson. If there is one the Leaflet will bind a popup to that feature with the contents equal to the value of the 'popup' property
https://github.com/rstudio/leaflet/blob/master/javascript/src/methods.js#L493

The problem is if you don't have one and most geojson's won't have a 'popup' property, then you have to add on on the R side. i.e. convert geojson string to a list and iteratively add popup property to each feature and convert it back to geojson string.

2) Convert geojson to a sp object in R, and use the popup features of add(PolyLines/Polygons/Markers) etc.
This is not a bad option as the sp object handling is way more elegant that geojson string or list.

Demo http://rpubs.com/bhaskarvk/leaflet-geojson (I don't have popups there only label, but you get the idea).

3) A middle ground, use leaflet.extra's addGeoJsonChoropleth which allows you to specify any property to a custom JS code to determine your popup content.
e.g. http://rpubs.com/bhaskarvk/geojson-choropleth

I like 3 the best coz it allows me to add a GeoJSON with no modification or conversion required on R side. The only issue there is the coloring is done on the JS side, and it uses chroma.js supplied pallets, while 1, and 2 allow you to use the coloring technique that is consistent with other add(Shape) methods.

**Comment by bhaskarvk** [comment]
Demo w/ all 3 approaches
http://rpubs.com/bhaskarvk/geojson-popups
& code
https://github.com/bhaskarvk/geojason-test

**Comment by bhaskarvk** [comment]
Just use `leaflet.extras::addGeoJSONv2()`, it's a feature rich alternative to `leaflet::addGeoJSON`.
See example code http://rpubs.com/bhaskarvk/geojsonv2
