### ISSUE TITLE
Leaflet 0.7.7 problem in internet explorer and edge

### ISSUE THREAD

**Issue by clausgp** [rstudio/leaflet#353]
Issue with leaflet/shiny in internet explorer and edge with github version of rstudio/leaflet

Reproducible example : leafletProxy example at https://rstudio.github.io/leaflet/shiny.html

In internet explorer and edge the map will initialize slowly and ‘hang’ when adjusting the sliders. There is no problem with chrome or firefox.

The problem seems to originate with leaflet version 0.7.7 as it starts with the 2nd commit on 22/9/2016. Reverting to the prior commit (with leaflet 0.7.3) - internet explorer and edge will work normally.

According to https://github.com/Leaflet/Leaflet/issues/4041 and https://github.com/Leaflet/Leaflet/issues/4357 this is a known problem that seems to be fixed with leaflet 1.0.0 betas or 0.7.7.1

**Comment by bhaskarvk** [comment]
Upgrading to 0.7.7.1 should be very trivial. @jcheng5 Need a PR ?

**Comment by bhaskarvk** [comment]
Looks like 0.7.7.1 is not officially released.
As per Leaflet/Leaflet#4357 it has been fixed in 
https://github.com/davojta/Leaflet/commits/stable_0_7_7_1_release, but this fork has diverged from the Original Leaflet 0.7 branch https://github.com/Leaflet/Leaflet/commits/0.7.

@jcheng5 How comfortable are you with using  davojta's fork for this, given that it's not official leaflet and diverges from the official branch ?

A quick solution could be to fork davojta's fork and rebase it on top of original branch, but I don't have time for that for now.

**Comment by bhaskarvk** [comment]
@clausgp Could you try 

```r
devtools::install_github('bhaskarvk/leaflet', ref='fix-upstream-353')
```

And let me know if it fixes the problem. After you confirm I can create a proper PR

**Comment by clausgp** [comment]
@bhaskarvk I can confirm that this fixes the problem with internet explorer.
