### ISSUE TITLE
Raster mapping according to custom bins.

### ISSUE THREAD

**Issue by noriegaedu** [rstudio/leaflet#468]
Using the same bin values the outputs of `rastervis` and `leaflet` packages doesn't match for a raster file.
[rastervis output](https://i.imgur.com/3MbmSQd.png) & [leaflet output](https://i.imgur.com/vB0GFHU.png).

Some of the spatial patterns are different and wonder why. Here is the code to create both outputs:
[raster file](https://drive.google.com/open?id=0B7mw858dxh5MODZqSHNHbFR3clU)

library(leaflet) ; library(rastervis) ; library(raster) ; library(tidyverse)
r <- raster('raster.tif')
colores <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", 
                          "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99", "#b15928")
at <- seq(0, 4800, 400)

**# Rastervis**:
levelplot(r, at = at , 
          colorkey = list(at = at, labels = list(at = at)), 
          xscale.components = xscale.raster.subticks,
          yscale.components = yscale.raster.subticks, 
          col.regions = colores)

**# Leaflet**:
cb <- colorBin(palette = colores, bins = at, domain = at)

leaflet() %>% 
    setView(-67.5,-16, zoom = 7) %>%
    addRasterImage(r, colors = cb) %>%
    addLegend(pal = cb, values = at)

**Comment by tim-salabim** [comment]
This is a matter of projecting the raster to the web mercator projection used by leaflet. When we do the same to your raster, the rasterVis plot looks identical.

```r
rwms = projectRaster(
  r, 
  projectExtent(
    r, 
    crs = "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
  )
)

levelplot(rwms, at = at ,
          colorkey = list(at = at, labels = list(at = at)),
          xscale.components = xscale.raster.subticks,
          yscale.components = yscale.raster.subticks,
          col.regions = colores)
```

**Comment by noriegaedu** [comment]
Yes, changing the projection fixes the issue but I wonder which output describes best the spatial pattern. Using ArcGis and QGIS both outputs match the `rasterVis` output and in this coordinate (-68.379, -15.864) it is crucial to define which output is the most accurate. Should I change projections? Is it possible to change projections to the leaflet output? Any advice is welcome.

**Comment by tim-salabim** [comment]
if you are interested in the value of the raster cell covering -68.379, -15.864 you should query the raster directly using e.g. `cellFromXY` or `over`. leaflet is a viewer, not more not less. QGIS and ArcGis support raster viewing in arbitrary crs (longlat in your case) when you don't load a background map, that's why the outputs match. However, when you load a background map those GIS systems will also have to re-project that raster layer to match the web mercator projection as otherwise raster and map wouldn't line up. 
Regarding your concern about accuracy, I'd suggest having a search for studies that related projection errors to measurement errors, which, especially in the case of precipitation measurements, I think are likely to conclude that measurement errors are much larger than any errors introduced by re-projecting the data to another crs (especially close to the equator). But that is just a (educated) guess. Still, worrying about accuracy on a map with 400mm precipitation bins seems a little over-concerned.

**Comment by noriegaedu** [comment]
I appreciate the info and your time. Thx.
