### ISSUE TITLE
addCircleMarkers not draggable

### ISSUE THREAD

**Issue by coolbanans** [rstudio/leaflet#480]
It appears that markerOptions(draggable = T) doesn't actually make a CircleMarker draggable:

```
map <- leaflet() %>% 
  addTiles() %>% 
  addMarkers(lng = -123.251,
             lat = 49.263, 
             popup = "Can drag",
             options = markerOptions(draggable = T)) %>% 
  addCircleMarkers(lng = -123.261,
                   lat = 49.273, 
                   popup = "Can't drag",
                   fillColor= "red", opacity = 1,
                   options = markerOptions(draggable = T)) %>% 
  setView(lng = -123.251,
          lat = 49.263,
          zoom = 13)

map
```

**Comment by bhaskarvk** [comment]
CircleMarker is actually instance of the Javascript Object `L.Path` rather than `L.Marker`, which is not draggable by default. If you install `leaflet.extras` and add the Draw toolbar to your map, then all Paths are draggable.

```
library(leaflet.extras)
map %>% addDrawToolbar()
```

In future release we might provide an option to enable path dragging w/o needing to add the draw tool bar, but I think this will do for now.
