### ISSUE TITLE
using from devtools load_all

### ISSUE THREAD

**Issue by barryrowlingson** [rstudio/leaflet#52]
If I install via install_github then the package works fine. But if I pull it and try load_all("./leaflet") then the resulting web page is blank. 

The HTML is there, but bits are missing. The head is:

```r
<head>
<meta charset="utf-8"/>
<script src="lib/htmlwidgets-0.3.2/htmlwidgets.js"></script>
<script src="lib/leaflet-binding-0.0.10/leaflet.js"></script>

</head>
```

whereas a working install has some other script tags and I guess that pulls in the code that does the work. Is the package trying to get some things that aren;t in the right place when its not truly installed? 

Or am I doing it wrong again...

**Comment by yihui** [comment]
I noticed the problem from day one. That is a general **htmlwidgets** issue, not specific to **leaflet** here. The culprit is `system.file()`, or **devtools** -- although **devtools** has tried to "fix" `system.file` in base R during `load_all()` with its own version of `sytem.file`, it cannot fix the system.file() calls that have been written in other packages, e.g. the system.file() calls may be fixed in **leaflet**, but the system.file() in **htmlwidgets** is still the real system.file(). So two options for you:

- build and install using the official approach;
- or see if you can make **devtools** even **smarter** (e.g. use dirtier hacks like `assignInNamespace`);

Honestly I just click the button Build & Reload in RStudio when I develop things in **leaflet**. Three or five seconds are not long enough to bother me :)

**Comment by wch** [comment]
There's actually a PR for devtools that would address this issue: hadley/devtools#744, but it hasn't been merged.

**Comment by ijlyttle** [comment]
Hi,

@jennybc suggested that I raise the possibility that `fs::path_package()` could be used to address this problem (r-lib/fs#175). Also raising this in r-lib/pkgload#69.

I don't know well enough the internals of pkgload, htmtools, or htmlwidgets to offer any opinions, but I am happy to file issues in the right places, if you can suggest them 🙂
