### ISSUE TITLE
Spacing below leaflet widgets

### ISSUE THREAD

**Issue by aoles** [rstudio/leaflet#542]
Hi,

Vertical spacing after leaflet widgets is left unset which results in no spacing between them and the succeeding content such as paragraph text or code chunks, as [here](https://giscience.github.io/openrouteservice-r/articles/openrouteservice.html#directions) for example. I was wondering whether improving this by setting some padding in your package's css code would make sense - please let me know what do you think.

Best,
Andrzej

**Comment by schloerke** [comment]
Hi @aoles,

I do not believe we should set any css that is outside of the widget.  Once outside the widget, I believe it is the user or layout engine responsibility.  

I'm going to close this issue here, but I've submited a general htmlwidgets margin-bottom issue (https://github.com/yihui/knitr/issues/1543) to knitr.  

Best,
Barret
