### ISSUE TITLE
Custom tile layer not visualized: KOMPASS maps

### ISSUE THREAD

**Issue by adrfantini** [rstudio/leaflet#543]
I am trying to visualize KOMPASS maps like the ones visualized [here](https://dominique92.github.io/MyLeaflet/src/Leaflet.Map.MultiVendors/) (select layer "Autriche").

The custom map URL, according to [the source](https://github.com/Dominique92/Leaflet.Map.MultiVendors/blob/4a79f2e0783ea93be23bf2154dea64cabede824e/src/layers/OSM.js), is `http://ec{s}.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20{l}&TileX={x}&TileY={y}&ZoomLevel={z}`.

However, issuing:
```R
library(leaflet)
leaflet() %>% addTiles(urlTemplate='http://ec0123.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20{l}&TileX={x}&TileY={y}&ZoomLevel={z}')
```
I am returned a grey empty map.
I tried forcing `{s}` to `0123` and `{t}` to `Touristik`, as in the linked Javascript working example, but it did not change the result.

 What am I missing?

**Comment by schloerke** [comment]
When I run your addTiles example, I receive a javascript error stating `No value provided for variable {l}`.  

https://github.com/Dominique92/Leaflet.Map.MultiVendors/blob/4a79f2e0783ea93be23bf2154dea64cabede824e/src/layers/OSM.js#L42 Shows that `l` is defined as `Touristik`.  

Substituting that in...
``` r
library(leaflet)                                                                                                                                             
                                                                                                                                                             
leaflet() %>%
  addTiles(urlTemplate='http://ec0123.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20Touristik&TileX={x}&TileY={y}&ZoomLevel={z}') %>%
  setView(2.5, 47, zoom = 6)                                                                                                                                   
```

![](https://i.imgur.com/PnaxM6R.png)


The map now works, but it returning null images... As a guess, I changed the subdomain to 0 (like the example) instead of 0123.

``` r
leaflet() %>%
  addTiles(urlTemplate='http://ec0.cdn.ecmaps.de/WmsGateway.ashx.jpg?Experience=kompass&MapStyle=KOMPASS%20Touristik&TileX={x}&TileY={y}&ZoomLevel={z}') %>%
  setView(2.5, 47, zoom = 6)                                                                                                                                   
```

![](https://i.imgur.com/U0AW9uO.png)

<br/><br/>
Thank you for the examples to work with!

\-Barret

**Comment by adrfantini** [comment]
Thank you! Awesome!
