### ISSUE TITLE
RStudio crashes when using `addLayersControl(baseGroups = ...))` and clicking on a radio button

### ISSUE THREAD

**Issue by daattali** [rstudio/leaflet#573]
When using the `baseGroups` option in `addLayerControl()`, radio buttons appear to select a layer. Inside RStudio Viewer, clicking on the labels of the radio buttons is fine, but clicking on the actual circles of the radio buttons crashes RStudio. This does not happen in a browser or with `overlayGroups` (checkboxes vs radio).

Windows 7
latest stable version of leaflet (2.0.1), htmlwidgets (1.2), and rstudio (1.1.456)

Code to reproduce (taken from https://rstudio.github.io/leaflet/showhide.html and modified to be as minimal as possible):

```r
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addCircles(data = quakes, ~long, ~lat, group = "Quakes") %>%
  addPolygons(data = quakes[chull(quakes$long, quakes$lat),], lng = ~long, lat = ~lat,
              group = "Outline") %>%
  addLayersControl(
    baseGroups = c("Quakes", "Outline")
  )
```

GIF of crash:

![leafletbug](https://user-images.githubusercontent.com/952340/43584831-2e31a450-966c-11e8-9885-770b078c3d65.gif)

[cross posted on [rstudio repo](https://github.com/rstudio/rstudio/issues/3251), please close one and leave it open on the relevant repo]

**Comment by schloerke** [comment]
Thank you @daattali for the great description!

Can you please test on your machine on a **daily** version of RStudio? https://dailies.rstudio.com/ 

I **can** reproduce the crash on a windows 7 vm. I do **NOT** get the crash with a daily build of RStudio.  (I can not reproduce the crash on mac.)

I believe this is a IDE issue over a leaflet issue.  So I am going to close this issue here and tag myself in the IDE issue to keep track.  My guess is that there will not be a fix as the rendering within windows in 1.1.x is not kind and 1.2.x fixes many, many issues for windows users.
