### ISSUE TITLE
Re: troublesome coordinates

### ISSUE THREAD

**Issue by johnpcauchi** [rstudio/leaflet#734]
---
Hi. Why is it that when I try these particular coordinates, it doesn't register them on a map (it specifies somewhere above the northern edge of the map!).

Note that I have tried other coordinates as suggested online and they've all worked. This particular one doesn't, however.

Would appreciate your insight.

```r
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(-9.751, 143.409, zoom = 12) %>%
  addPopups(
    -9.751, 143.409,
    '<b>Masig Island</b>, Torres Strait'
  )
```

**Comment by jcheng5** [comment]
You have your latitude and longitude reversed--or, alternately, you may choose to take the position that `setView` and `addPopup` have their latitude and longitude arguments reversed. For historical reasons, they take longitude first and then latitude. (I wish I could go back and undo that decision.)

If you like, just use `lat = -9.751, lng = 143.409` instead of reversing the order.

**Comment by johnpcauchi** [comment]
Thank you! It worked like a charm :) Will keep that in mind for future uses of this function.
