### ISSUE TITLE
addMarkers shows a broken image

### ISSUE THREAD

**Issue by philbowsher** [rstudio/leaflet#791]
addMarkers is hiccupping 

https://rstudio.github.io/leaflet/markers.html

shows a broken image above.

**Comment by jcheng5** [comment]
Thanks Phil. Dupe of https://github.com/rstudio/leaflet/issues/782, new release that fixes this is already submitted to CRAN.

**Comment by jcheng5** [comment]
Actually, sorry, the _custom_ markers on that page that are failing (e.g. https://leafletjs.com/examples/custom-icons/leaf-green.png) are doing so because the author of leaflet.js has temporarily moved the entire site to a subdirectory and replaced the original website with a denunciation of the invasion of Ukraine. I'll put them somewhere else I guess.

**Comment by jcheng5** [comment]
Fixed that page.
