### ISSUE TITLE
Way to set scrollWheelZoom

### ISSUE THREAD

**Issue by chocksmith** [rstudio/leaflet#84]
Leaflet has many features that are not accessible from shiny.
scrollWheelZoom is probably one of the most important ones for those who use Mac. 
Without setting this to false, it zooms whenever you try to move around with mousepad gestures. It is a pain.

Please, consider implement a way to set/reset/access "hidden" leaflet features like this.

Tks

**Comment by yihui** [comment]
We have a missing piece in htmlwidgets, i.e. the ability to set widget initialization options: https://github.com/rstudio/leaflet/blob/770d25f79025/inst/htmlwidgets/leaflet.js#L652-L657 (`scrollWheelZoom` is one of the initialization options) I'm not sure if it is easy to address this issue in htmlwidgets. 

Cc @jjallaire @jcheng5 @ramnathv @timelyportfolio

**Comment by jcheng5** [comment]
It's not necessary to address it in htmlwidgets. If the initialization depends on `x`, then it should be performed in `renderValue`, not `initialize`. dygraphs for example does this:

https://github.com/rstudio/dygraphs/blob/9295cf603ecbf4ff05cf2470d2e505810bfa8d71/inst/htmlwidgets/dygraphs.js#L95

It doesn't make sense to try to make `x` available to `initialize`--what happens if the value of `scrollWheelZoom` changes from one value of `x` to another? `initialize` is by definition called once.

**Comment by jcheng5** [comment]
As to the original request--that is a pain. Ideally I'd like to find a solution that doesn't unintentionally zoom like now, but also doesn't disable the gesture. I wonder if it's possible to detect whether the scroll operation began while the mouse cursor was over the map, and ignore if not...

**Comment by yihui** [comment]
Here is a solution: http://cliffcloud.github.io/Leaflet.Sleep/

**Comment by jacob-ogre** [comment]
Thanks, @yihui...adding Leaflet.Sleep.js and sourcing in ui.R seems to work very well.

**Comment by jcheng5** [comment]
We ended up implementing our own similar mechanism, hopefully this is not such a problem anymore.
