### ISSUE TITLE
leaflet is dependent on R3.6.0 via leaflet.providers, not R3.1.0 as per DESCRIPTION

### ISSUE THREAD

**Issue by PietrH** [rstudio/leaflet#880]
We noticed that leaflet has indirectly increased it's minimum R version requirement from 3.1.0 to 3.6.0 during an update of our package witch is dependent on leaflet: https://github.com/inbo/camtraptor/actions/runs/6071680606/job/16470188762

Currently installing leaflet on an R version below R3.6.0 will fail: 

```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency leaflet
  * leaflet: Can't install dependency leaflet.providers (>= 1.8.0)
  * leaflet.providers: Needs R >= 3.6
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
```

Causing packages dependent on leaflet to also fail on versions lower than 3.6.0

This is because leaflet.providers is dependent on R3.6.0 as per https://github.com/rstudio/leaflet.providers/commit/d1600efcfbba6d271939a006cde42e54efc83829

This can be fixed by upping the minimum version of R in [DESCRIPTION](https://github.com/rstudio/leaflet/blob/1c06a658d7aba355f3f602ee52a8266a6a3a07a1/DESCRIPTION#L51C17-L51C17)

**Comment by gadenbuie** [comment]
@schloerke Do you remember if there was a specific motivation for bumping the minimum version of R in leaflet.providers?

**Comment by schloerke** [comment]
`usethis::use_tidy_upkeep_issue()` prompted me.

Implementation details:
* https://github.com/r-lib/usethis/blob/467ff57f92afb34878dc411c46e3f0de029ceea4/R/upkeep.R#L275
* Which points to https://www.tidyverse.org/blog/2019/04/r-version-support/


Since we are not testing beyond `oldrel-4`, then I'd rather not allow for it.

---------------------------

We can bump the leaflet min R version in `leaflet`, but this won't solve your GitHub action issue. If the change was made, the Action would error and say that `leaflet` can't be installed.

To get around this you're going to have to use a URL install for leaflet providers. 

In your DESCRIPTION file, you can get around this with:

```
Config/Needs/check:
    url::https://github.com/rstudio/leaflet.providers/archive/refs/tags/v1.9.0.zip
```

... but I strongly suggest you update your test suite to use modern R versions. Then this situation is avoided entirely.


---------------------------

[`{leaflet.providers}` will be receiving an update](https://github.com/rstudio/leaflet.providers/issues/32). We'll downgrade the min R version there.

**Comment by gadenbuie** [comment]
Thanks for the report, @PietrH! I rolled back the minimum R version requirement in leaflet.providers. You can temporarily use the version of leaflet.providers from GitHub until we release the next version of that package.

Note also that we actively support the current and previous 4 R versions [as described here](https://www.tidyverse.org/blog/2019/04/r-version-support/), so the minimum R version required by leaflet.providers is theoretical and not practical.

**Comment by PietrH** [comment]
Thanks everyone for looking into it, we've bumped our minimum R requirement to 3.6.0 up from 3.5.0, we are now in line with the tidyverse. Personally I think there is an argument to be made to long term support R3.6 beyond 2024, but be that as it may our problem is currently solved.
