### ISSUE TITLE
Broken basemaps on {pkgdown} site

### ISSUE THREAD

**Issue by jack-davison** [rstudio/leaflet#912]
Good morning,

Just highlighting there are broken basemaps in the `{pkgdown}` site.

This is almost certainly to do with #883. Interestingly, the basemaps load in an interactive session, but not on the hosted website.

e.g., https://rstudio.github.io/leaflet/articles/basemaps.html:

![image](https://github.com/rstudio/leaflet/assets/45171616/b9fc9019-53d5-42d5-bf75-e84167c7d20c)

**Comment by gadenbuie** [comment]
Thanks for the issue and PR @jack-davison!

> This is almost certainly to do with #883. Interestingly, the basemaps load in an interactive session, but not on the hosted website.

That's right, and the behavior is explained in this comment: https://github.com/rstudio/leaflet/issues/883#issuecomment-2026450483

I think your PR is headed in the right direction, but I'd also like to try to solve this using the methods described in the above linked comment so that we have experience with it. That said, it does make sense for us to reduce our usage of the `Stadia.Stamen*` basemaps in our docs.

**Comment by jack-davison** [comment]
Understood @gadenbuie!

Thought I'd just do you one better than pointing out the broken examples and do you a short-term fix, but if you're keen to have Stadia included from the off then that's fair enough!

**Comment by gadenbuie** [comment]
Thanks again for the PR @jack-davison!
